INSERT INTO GC_PROPIETARIOS (NOMBRE, APELLIDO1, APELLIDO2, EMAIL, NUMERO_DOCUMENTO)
VALUES ('Alberto', 'Peñate', 'Marrero', 'alpema@gmail.com', '78711678C');


INSERT INTO GC_VIVIENDAS(DESCRIPCION_VIVIENDA, NUMERO_VIVIENDA, PORTAL_VIVIENDA, COEFICIENTE_VIVIENDA, ID_PROPIETARIO, CUOTA, AUD_APL, AUD_USR)
VALUES ('Apartamento N 12', '12', 'PORTAL 1', 1, 1.30, 'NO-APL', 'ZMS');
